"""crear tablas modulo asistencia

Revision ID: 58b4ab9f2020
Revises: b416e5e568e2
Create Date: 2026-08-27 20:08:15.092256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b4ab9f2020'
down_revision: Union[str, Sequence[str], None] = 'b416e5e568e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_asistencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horas_trabajadas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('horas_extra', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('origen', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_asistencia_empleado_id'), 'registros_asistencia', ['empleado_id'], unique=False)
    op.create_table('saldos_vacaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('dias_disponibles', sa.Integer(), nullable=False),
    sa.Column('dias_tomados', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'anio', name='uq_saldo_vacaciones_empleado_anio')
    )
    op.create_index(op.f('ix_saldos_vacaciones_empleado_id'), 'saldos_vacaciones', ['empleado_id'], unique=False)
    op.create_table('solicitudes_permiso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('VACACIONES', 'ENFERMEDAD', 'PERSONAL', 'LUTO', 'MATERNIDAD_PATERNIDAD', 'OTRO', name='tipopermisoenum', native_enum=False, length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estadosolicitudenum', native_enum=False, length=20), nullable=False),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_permiso_empleado_id'), 'solicitudes_permiso', ['empleado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_permiso_empleado_id'), table_name='solicitudes_permiso')
    op.drop_table('solicitudes_permiso')
    op.drop_index(op.f('ix_saldos_vacaciones_empleado_id'), table_name='saldos_vacaciones')
    op.drop_table('saldos_vacaciones')
    op.drop_index(op.f('ix_registros_asistencia_empleado_id'), table_name='registros_asistencia')
    op.drop_table('registros_asistencia')
    # ### end Alembic commands ###
