"""crear tablas modulo capacitacion

Revision ID: 72b3bbc688b9
Revises: efb224a573e0
Create Date: 2026-08-27 20:08:41.284998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b3bbc688b9'
down_revision: Union[str, Sequence[str], None] = 'efb224a573e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('duracion_horas', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('INSCRITO', 'EN_PROGRESO', 'COMPLETADO', 'ABANDONADO', name='estadoinscripcionenum', native_enum=False, length=20), nullable=False),
    sa.Column('progreso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_finalizacion', sa.Date(), nullable=True),
    sa.Column('certificado_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripciones_curso_id'), 'inscripciones', ['curso_id'], unique=False)
    op.create_index(op.f('ix_inscripciones_empleado_id'), 'inscripciones', ['empleado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inscripciones_empleado_id'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_curso_id'), table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_table('cursos')
    # ### end Alembic commands ###
