"""crear tablas modulo desempeno

Revision ID: b416e5e568e2
Revises: cbd6a3fdf612
Create Date: 2026-08-24 20:25:33.567679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b416e5e568e2'
down_revision: Union[str, Sequence[str], None] = 'cbd6a3fdf612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos_evaluacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('evaluador_id', sa.Uuid(), nullable=False),
    sa.Column('ciclo_id', sa.Uuid(), nullable=False),
    sa.Column('calificacion_final', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('plan_mejora', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_ciclo_id'), 'evaluaciones', ['ciclo_id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_empleado_id'), 'evaluaciones', ['empleado_id'], unique=False)
    op.create_table('objetivos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('ciclo_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('meta_valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivos_ciclo_id'), 'objetivos', ['ciclo_id'], unique=False)
    op.create_index(op.f('ix_objetivos_empleado_id'), 'objetivos', ['empleado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objetivos_empleado_id'), table_name='objetivos')
    op.drop_index(op.f('ix_objetivos_ciclo_id'), table_name='objetivos')
    op.drop_table('objetivos')
    op.drop_index(op.f('ix_evaluaciones_empleado_id'), table_name='evaluaciones')
    op.drop_index(op.f('ix_evaluaciones_ciclo_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_table('ciclos_evaluacion')
    # ### end Alembic commands ###
