"""crear tablas modulo reclutamiento

Revision ID: cbd6a3fdf612
Revises: ddcdd58ceb99
Create Date: 2026-08-24 18:53:05.952579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd6a3fdf612'
down_revision: Union[str, Sequence[str], None] = 'ddcdd58ceb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatos_email'), 'candidatos', ['email'], unique=False)
    op.create_table('vacantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('departamento_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PUBLICADA', 'CERRADA', name='estadovacanteenum', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('numero_posiciones', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postulaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vacante_id', sa.Uuid(), nullable=False),
    sa.Column('candidato_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('RECIBIDA', 'EN_FILTRO', 'ENTREVISTA', 'OFERTA', 'CONTRATADO', 'RECHAZADA', name='estadopostulacionenum', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('puntaje_filtro', sa.Integer(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postulaciones_candidato_id'), 'postulaciones', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_postulaciones_vacante_id'), 'postulaciones', ['vacante_id'], unique=False)
    op.create_table('entrevistas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('postulacion_id', sa.Uuid(), nullable=False),
    sa.Column('entrevistador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', 'TELEFONICA', name='modalidadentrevistaenum', native_enum=False, length=20), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entrevistador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevistas_postulacion_id'), 'entrevistas', ['postulacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entrevistas_postulacion_id'), table_name='entrevistas')
    op.drop_table('entrevistas')
    op.drop_index(op.f('ix_postulaciones_vacante_id'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_candidato_id'), table_name='postulaciones')
    op.drop_table('postulaciones')
    op.drop_table('vacantes')
    op.drop_index(op.f('ix_candidatos_email'), table_name='candidatos')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
