"""crear tablas modulo empleados

Revision ID: ddcdd58ceb99
Revises: 8d7ca9530a47
Create Date: 2026-08-24 18:31:56.118789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcdd58ceb99'
down_revision: Union[str, Sequence[str], None] = '8d7ca9530a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('gerente_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puestos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('departamento_id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_empleado', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula_o_dni', sa.String(length=30), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estadoempleadoenum', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('puesto_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('departamento_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['puestos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_empleados_cedula_o_dni'), 'empleados', ['cedula_o_dni'], unique=True)
    op.create_index(op.f('ix_empleados_codigo_empleado'), 'empleados', ['codigo_empleado'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('INDEFINIDO', 'TEMPORAL', 'POR_HORAS', 'PRACTICA', name='tipocontratoenum', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('salario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('documento_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'FINALIZADO', 'CANCELADO', name='estadocontratoenum', native_enum=False, length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_empleado_id'), 'contratos', ['empleado_id'], unique=False)
    op.create_table('datos_legales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('numero_seguridad_social', sa.String(length=50), nullable=True),
    sa.Column('beneficiarios', sa.Text(), nullable=True),
    sa.Column('informacion_emergencia', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id')
    )
    op.create_table('documentos_expediente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('CEDULA', 'CV', 'CONTRATO', 'CERTIFICADO', 'TITULO', 'OTRO', name='tipodocumentoenum', native_enum=False, length=20), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cargado_por', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_expediente_empleado_id'), 'documentos_expediente', ['empleado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_expediente_empleado_id'), table_name='documentos_expediente')
    op.drop_table('documentos_expediente')
    op.drop_table('datos_legales')
    op.drop_index(op.f('ix_contratos_empleado_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_empleados_codigo_empleado'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_cedula_o_dni'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_table('puestos')
    op.drop_table('sucursales')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
