"""crear tablas modulo nomina

Revision ID: efb224a573e0
Revises: 58b4ab9f2020
Create Date: 2026-08-27 20:08:28.374411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb224a573e0'
down_revision: Union[str, Sequence[str], None] = '58b4ab9f2020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos_nomina',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'PROCESADO', 'CERRADO', name='estadoperiodoenum', native_enum=False, length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nominas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('periodo_id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('salario_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deducciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_bonificaciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salario_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominas_empleado_id'), 'nominas', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_nominas_periodo_id'), 'nominas', ['periodo_id'], unique=False)
    op.create_table('conceptos_nomina',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nomina_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('SALARIO_BASE', 'HORAS_EXTRA', 'BONIFICACION', 'DEDUCCION_SFS', 'DEDUCCION_AFP', 'DEDUCCION_ISR', 'OTRO', name='tipoconceptoenum', native_enum=False, length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nomina_id'], ['nominas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptos_nomina_nomina_id'), 'conceptos_nomina', ['nomina_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conceptos_nomina_nomina_id'), table_name='conceptos_nomina')
    op.drop_table('conceptos_nomina')
    op.drop_index(op.f('ix_nominas_periodo_id'), table_name='nominas')
    op.drop_index(op.f('ix_nominas_empleado_id'), table_name='nominas')
    op.drop_table('nominas')
    op.drop_table('periodos_nomina')
    # ### end Alembic commands ###
